CREATE INDEX IDX_CMM6601_REG_DTM
ON CMM6601 (REG_DTM)
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
    INITIAL 64K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
)
TABLESPACE TS_LUNA_IDX01
COMPUTE STATISTICS
ONLINE;

CREATE INDEX IDX_DPL1400_BLD
ON DPL1400 (PRJ_ID, BLD_RESULT_CD)
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
    INITIAL 192K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
)
TABLESPACE TS_LUNA_IDX01
COMPUTE STATISTICS
ONLINE;

CREATE INDEX IDX_LIC_GRP_ID
ON STM3000 (LIC_GRP_ID)
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
    INITIAL 64K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
)
TABLESPACE TS_LUNA_IDX01
COMPUTE STATISTICS
ONLINE;

CREATE INDEX IDX_PRJ1000_PRJ_GRP_ID
ON PRJ1000 (PRJ_GRP_ID)
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
    INITIAL 64K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
)
TABLESPACE TS_LUNA_IDX01
COMPUTE STATISTICS
ONLINE;

CREATE INDEX IDX_PRJ_DPL_SIGN_DTM
ON DPL1200 (PRJ_ID, DPL_ID, SIGN_DTM)
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
    INITIAL 64K
)
TABLESPACE TS_LUNA_IDX01
COMPUTE STATISTICS
ONLINE;

CREATE INDEX IDX_REQ5000_REG_DTM
ON REQ5000 (PRJ_ID, REG_DTM)
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
    INITIAL 64K
)
TABLESPACE TS_LUNA_IDX01
COMPUTE STATISTICS
ONLINE;

CREATE INDEX IDX_REQ6000_REG_DTM
ON REQ6000 (REG_DTM)
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
    INITIAL 64K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
)
TABLESPACE TS_LUNA_IDX01
COMPUTE STATISTICS
ONLINE;

CREATE INDEX IDX_REQ6001_REG_DTM
ON REQ6001 (PRJ_ID, REG_DTM)
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
    INITIAL 128K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
)
TABLESPACE TS_LUNA_IDX01
COMPUTE STATISTICS
ONLINE;

CREATE INDEX IDX_REQ_CLS_TYPE
ON REQ4100 (REQ_CLS_TYPE)
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
    INITIAL 64K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
)
TABLESPACE TS_LUNA_IDX01
COMPUTE STATISTICS
ONLINE;

CREATE INDEX IDX_REQ_PRJ_ID
ON REQ4100 (PRJ_ID)
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
    INITIAL 64K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
)
TABLESPACE TS_LUNA_IDX01
COMPUTE STATISTICS
ONLINE;

CREATE INDEX IDX_REQ_PRO_TYPE
ON REQ4100 (REQ_PRO_TYPE)
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
    INITIAL 64K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
)
TABLESPACE TS_LUNA_IDX01
COMPUTE STATISTICS
ONLINE;

CREATE INDEX IDX_STM4203_WIDGET_LIST
ON STM4203 (LIC_GRP_ID, MENU_ID, PRJ_ID)
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
    INITIAL 64K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
)
TABLESPACE TS_LUNA_IDX01
COMPUTE STATISTICS
ONLINE;

CREATE INDEX IDX_STM4204_WIDGET_LIST
ON STM4204 (LIC_GRP_ID, MENU_ID, PRJ_ID)
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
    INITIAL 128K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
)
TABLESPACE TS_LUNA_IDX01
COMPUTE STATISTICS
ONLINE;

CREATE INDEX IDX_STM6000_UPPER
ON STM6000 (UPPER_DEPT_ID, LVL, LIC_GRP_ID)
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE (
    INITIAL 64K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
)
TABLESPACE TS_LUNA_IDX01
COMPUTE STATISTICS
ONLINE;
